// ©2025, ANSYS Inc. Unauthorized use, distribution or duplication is prohibited.
// <auto-generated/>

namespace Projects;

[global::System.CodeDom.Compiler.GeneratedCode("Aspire.Hosting", null)]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated code.")]
[global::System.Diagnostics.DebuggerDisplay("Type = {GetType().Name,nq}, ProjectPath = {ProjectPath}")]
public class pic_ApiService : global::Aspire.Hosting.IProjectMetadata
{
    public string ProjectPath => """..\pic.ApiService\pic.ApiService.csproj""";
}
