name: "Frogbot Scan Repository"
on: 
  pull_request_target: 
    # Triggers scan-pr flow for every opened/updated pull request
    types: [opened, synchronize] 
  push: 
    # Triggers scan-repo flow for every push to the specified branches
    branches:
      - main
  schedule:
    # The repository will be scanned every Monday at 00:00 GMT (Can be change according to your needs).
    - cron: "0 0 * * 1"
  workflow_dispatch: # The repository will be scanned on demand
  
permissions:
  contents: write
  pull-requests: write
  security-events: write
  # [Mandatory If using OIDC authentication protocol instead of JF_ACCESS_TOKEN]
  id-token: write
  
jobs:
  scan-repository:
    runs-on: ubuntu-latest-4-cores
    # container:
    #   # Official .NET SDK image with python3-virtualenv package installed. One-time manual creation.
    #   image: azuekubeacr03.azurecr.io/dotnet/sdk-python3-virtualenv:9.0.201-noble-amd64
    strategy:
      matrix:
        # The repository scanning will be triggered periodically on the following branches.
        branch: ["main"]
    steps:
      - uses: jfrog/frogbot@v2
        env:
          # [Mandatory]
          # JFrog platform URL
          # Accessible from GitHub-hosted runners.
          JF_URL: https://ansyscpp.jfrog.io/

          # [Mandatory if JF_USER and JF_PASSWORD are not provided]
          # JFrog access token with 'read' permissions on Xray service
          # JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

          # [Mandatory if JF_ACCESS_TOKEN is not provided]
          # JFrog username with 'read' permissions for Xray. Must be provided with JF_PASSWORD
          # JF_USER: ${{ secrets.JF_USER }}

          # [Mandatory if JF_ACCESS_TOKEN is not provided]
          # JFrog password. Must be provided with JF_USER
          # JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

          # [Mandatory]
          # The GitHub token is automatically generated for the job
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # [Mandatory]
          # The name of the branch on which Frogbot will perform the scan
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}

        # [Mandatory if using OIDC authentication protocol instead of JF_ACCESS_TOKEN]
        # Insert to oidc-provider-name the 'Provider Name' defined in the OIDC integration configured in the JPD
        with:
          oidc-provider-name: "github-actions-oidc"
          oidc-audience: GitHub ansys-internal CI/CD Pipelines
